[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "addictune-sdk"
version = "0.1.0"
description = "Python SDK for Addictune Radio API"
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
authors = [
    { name = "ukw2d" },
]
urls.Repository = "https://github.com/ukw2d/addictune-sdk"
dependencies = [
    "httpx>=0.28",
    "pydantic>=2.11",
]

[tool.hatch.build.targets.wheel]
packages = ["addictune_sdk"]

[dependency-groups]
dev = [
    "pytest>=9",
    "pytest-asyncio>=1",
    "pytest-mock>=3.15.1",
]
